/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.unidade04_eventosdomouse;

import java.awt.Color;

/**
 *
 * @author edwar
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlPrincipalMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlPrincipalMouseMoved(evt);
            }
        });
        pnlPrincipal.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pnlPrincipalMouseWheelMoved(evt);
            }
        });
        pnlPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPrincipalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlPrincipalMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMouseClicked
        lblMensagem.setText("Mouse clicado nas coordenadas: [" + evt.getX() +
                "," + evt.getY() + "]");
        System.out.println("Mouse clicado nas coordenadas: [" + evt.getX() +
                "," + evt.getY() + "]");
    }//GEN-LAST:event_pnlPrincipalMouseClicked

    private void pnlPrincipalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMouseDragged
        lblMensagem.setText("Mouse dragged nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        System.out.println("Mouse dragged nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
    }//GEN-LAST:event_pnlPrincipalMouseDragged

    private void pnlPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMouseEntered
        lblMensagem.setText("Mouse entrou no JPanel. Coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        System.err.println("Mouse entrou no JPanel. Coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        pnlPrincipal.setBackground(Color.GREEN);
    }//GEN-LAST:event_pnlPrincipalMouseEntered

    private void pnlPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMouseExited
        lblMensagem.setText("Mouse saiu do JPanel. Coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        System.err.println("Mouse saiu do JPanel. Coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        pnlPrincipal.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlPrincipalMouseExited

    private void pnlPrincipalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMouseMoved
        lblMensagem.setText("Mouse moveu nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        System.out.println("Mouse moveu nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
    }//GEN-LAST:event_pnlPrincipalMouseMoved

    private void pnlPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMousePressed
        lblMensagem.setText("Mouse pressionado nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        System.out.println("Mouse pressionado nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
    }//GEN-LAST:event_pnlPrincipalMousePressed

    private void pnlPrincipalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMouseReleased
        lblMensagem.setText("Mouse liberado nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        System.out.println("Mouse liberado nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
    }//GEN-LAST:event_pnlPrincipalMouseReleased

    private void pnlPrincipalMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pnlPrincipalMouseWheelMoved
        lblMensagem.setText("Rodinha do mouse rodada nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
        System.out.println("Rodinha do mouse rodada nas coordenadas: [" + evt.getX() +
         "," + evt.getY() + "]");
    }//GEN-LAST:event_pnlPrincipalMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
