package principal;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author IFTM
 */
public class FormCadVeiculos extends javax.swing.JFrame {
    
    private GerenciaCarros gc;
    private ArrayList<Carro> carros;
    private Carro ultimoVeiculoAcessado;
    private boolean flagBotaoNovoClicado;
    private boolean flagBotaoAlterarClicado;

    /**
     * Creates new form FormCadVeiculos
     */
    public FormCadVeiculos() {
        initComponents();
        carros = new ArrayList<>();
        gc = new GerenciaCarros(carros);
        iniciaBotoes();
        habDesabNavegacao(false);
        habDesabTela(false);
        ultimoVeiculoAcessado = null;
        flagBotaoAlterarClicado = false;
        flagBotaoNovoClicado = false;
        
        /* Componente não está funcionando corretamente. */
        ftfPreco.setVisible(false);
        configurarTfPreco();
    }

    private void iniciaBotoes(){
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    public void habDesabNavegacao(boolean valor){
        btnPrimeiro.setEnabled(valor);
        btnAnterior.setEnabled(valor);
        btnProximo.setEnabled(valor);
        btnUltimo.setEnabled(valor);
    }
    
    public void habDesabTela(boolean valor){
        tfMarca.setEnabled(valor);
        tfModelo.setEnabled(valor);
        spnAnoFab.setEnabled(valor);
        spnAnoMod.setEnabled(valor);
        tfPreco.setEnabled(valor);
//        ftfPreco.setEnabled(valor);
        
        if(valor && tfMarca.isFocusable())
            tfMarca.requestFocus();
    }
    
    public void btnNovoClicado(){
        limpaFormulario();
        
        habDesabTela(true);
        habDesabNavegacao(false);
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        
        flagBotaoNovoClicado = true;
    }
    
    public void btnSalvarClicado(){
        habDesabTela(false);
        habDesabNavegacao(true);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    }
    
    public void btnCancelarClicado(){
        habDesabTela(false);
        if(gc.relatorio().isEmpty()){
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            habDesabNavegacao(false);
        }
        else{
            btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            habDesabNavegacao(true);
        }
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        flagBotaoAlterarClicado = false;
        flagBotaoNovoClicado = false;
    }
    
    public void btnExcluirClicado(){
        habDesabTela(false);
        if(gc.relatorio().isEmpty()){
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            habDesabNavegacao(false);
        }
        else{
            btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            habDesabNavegacao(true);
        }
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
    
    public void btnAlterarClicado(){
        habDesabTela(true);
        habDesabNavegacao(false);
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        
        flagBotaoAlterarClicado = true;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfMarca = new javax.swing.JTextField();
        tfModelo = new javax.swing.JTextField();
        spnAnoFab = new javax.swing.JSpinner();
        spnAnoMod = new javax.swing.JSpinner();
        ftfPreco = new javax.swing.JFormattedTextField();
        try {
            javax.swing.text.MaskFormatter mask = new javax.swing.text.MaskFormatter("#,##0.00");
            mask.setPlaceholderCharacter('_');
            mask.setValueClass(Double.class);
            ftfPreco = new javax.swing.JFormattedTextField(mask);
            ftfPreco.setValue(0.0);
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
            ftfPreco = new javax.swing.JFormattedTextField(); // Cria um campo simples em caso de erro
        }
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblAnoFab = new javax.swing.JLabel();
        lblAnoMod = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfPreco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Veículos");

        spnAnoFab.setValue(2000);

        spnAnoMod.setValue(2000);

        ftfPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        ftfPreco.setEnabled(false);
        ftfPreco.setFocusable(false);
        ftfPreco.setRequestFocusEnabled(false);

        lblMarca.setDisplayedMnemonic('M');
        lblMarca.setLabelFor(tfMarca);
        lblMarca.setText("Marca");

        lblModelo.setDisplayedMnemonic('d');
        lblModelo.setLabelFor(tfModelo);
        lblModelo.setText("Modelo");

        lblAnoFab.setDisplayedMnemonic('F');
        lblAnoFab.setLabelFor(spnAnoFab);
        lblAnoFab.setText("Ano Fabricação");

        lblAnoMod.setDisplayedMnemonic('o');
        lblAnoMod.setLabelFor(spnAnoMod);
        lblAnoMod.setText("Ano Modelo");

        lblPreco.setDisplayedMnemonic('P');
        lblPreco.setLabelFor(ftfPreco);
        lblPreco.setText("Preço");

        btnNovo.setMnemonic('N');
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setMnemonic('S');
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setMnemonic('A');
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setMnemonic('x');
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPrimeiro.setText("<<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnProximo.setText(">");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setText(">>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnCancelar.setMnemonic('C');
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMarca)
                                            .addComponent(lblAnoFab))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnAnoFab)
                                        .addGap(75, 75, 75)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnoMod)
                                    .addComponent(lblModelo)
                                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnAnoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(ftfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(lblModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoFab)
                    .addComponent(lblAnoMod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnAnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAnoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(lblPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeiro)
                    .addComponent(btnUltimo)
                    .addComponent(btnProximo)
                    .addComponent(btnAnterior))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnNovoClicado();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String marca, modelo, log = "";
        float preco;
        
        marca = tfMarca.getText();
        if(marca.isEmpty())
            JOptionPane.showMessageDialog(this, "Marca deve ser preenchida.");
        else{
            modelo = tfModelo.getText();
            if(modelo.isEmpty())
                JOptionPane.showMessageDialog(this, "Modelo deve ser preenchido.");
            else{
                int anoFab = (int)spnAnoFab.getValue();
                if((anoFab < 1900) && (anoFab > LocalDate.now().getYear()))
                    JOptionPane.showMessageDialog(this, "Ano Fabricação inválido.");
                else{
                    int anoMod = (int)spnAnoMod.getValue();
                    if((anoMod < 1900) && (anoFab > LocalDate.now().getYear()))
                        JOptionPane.showMessageDialog(this, "Ano Fabricação inválido.");
                    else{
//                        preco = Float.parseFloat(ftfPreco.getText().trim());
                        String numericText = tfPreco.getText().replaceAll("[^0-9]", "");
                        preco = Float.parseFloat(numericText) / 100;
                        
                        /* Para pegar uma referência criada dentro do método 
                           sem ser pelo retorno no mesmo.                    */
                        Carro pegaReferenciaDoCarroCriado[] = new Carro[1];
                        
                        if(flagBotaoNovoClicado){
                            log = gc.incluir(marca, modelo, anoFab, anoMod, preco, 
                                    pegaReferenciaDoCarroCriado);
                            ultimoVeiculoAcessado = pegaReferenciaDoCarroCriado[0];
                            
                            flagBotaoNovoClicado = false;
                            
                            JOptionPane.showMessageDialog(this, "Inclusão efetuada com sucesso.");
                        }
                        
                        if(flagBotaoAlterarClicado){
                            log = gc.alterar(ultimoVeiculoAcessado, marca, modelo, 
                                    anoFab, anoMod, preco);
                            
                            flagBotaoAlterarClicado = false;
                            
                            JOptionPane.showMessageDialog(this, "Alteração efetuada com sucesso.");
                        }
                    }
                }
            }
        }
        
        btnSalvarClicado();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(ultimoVeiculoAcessado == null)
            limpaFormulario();
        else
            preencheFormulario(ultimoVeiculoAcessado);
        
        btnCancelarClicado();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        btnAlterarClicado();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Carro[] veiculoAnteriorOuPosterior = new Carro[1];
        String log;
        
        if(JOptionPane.YES_OPTION ==
                JOptionPane.showConfirmDialog(this,
                "Confirma exclusão?", "Confirmação de exclusão de veículo",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)){
            log = gc.excluir(ultimoVeiculoAcessado,veiculoAnteriorOuPosterior);
            
            if(log.equals("")){
                if(veiculoAnteriorOuPosterior[0] == null){
                    limpaFormulario();
                }
                else{
                    ultimoVeiculoAcessado = veiculoAnteriorOuPosterior[0];
                    preencheFormulario(ultimoVeiculoAcessado);
                }
            }
            else
                JOptionPane.showMessageDialog(this, "Problema na exclusão. Erro: " + log, 
                        "Erro na exclusão", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Confirmação não excluída.");
     
        btnExcluirClicado();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        ultimoVeiculoAcessado = gc.primeiroVeiculo();
        if(ultimoVeiculoAcessado != null)
            preencheFormulario(ultimoVeiculoAcessado);
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        ultimoVeiculoAcessado = gc.veiculoAnterior(ultimoVeiculoAcessado);
        if(ultimoVeiculoAcessado != null)
            preencheFormulario(ultimoVeiculoAcessado);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        ultimoVeiculoAcessado = gc.veiculoPosterior(ultimoVeiculoAcessado);
        if(ultimoVeiculoAcessado != null)
            preencheFormulario(ultimoVeiculoAcessado);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        ultimoVeiculoAcessado = gc.ultimoVeiculo();
        if(ultimoVeiculoAcessado != null)
            preencheFormulario(ultimoVeiculoAcessado);
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void preencheFormulario(Carro car){
        tfMarca.setText(car.getMarca());
        tfModelo.setText(car.getModelo());
        spnAnoFab.setValue(car.getAnoFabricacao());
        spnAnoMod.setValue(car.getAnoModelo());
        long preco = Math.round(car.getPreco() * 100);
        tfPreco.setText("R$" + (preco / 100) + "," + String.format("%02d", preco % 100));
//        ftfPreco.setValue(car.getPreco());
    }

    private void limpaFormulario(){
        tfMarca.setText("");
        tfModelo.setText("");
        spnAnoFab.setValue(2000);
        spnAnoMod.setValue(2000);
        tfPreco.setText("");
//        ftfPreco.setValue(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JFormattedTextField ftfPreco;
    private javax.swing.JLabel lblAnoFab;
    private javax.swing.JLabel lblAnoMod;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JSpinner spnAnoFab;
    private javax.swing.JSpinner spnAnoMod;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfPreco;
    // End of variables declaration//GEN-END:variables

private void configurarTfPreco() {
    ((AbstractDocument) tfPreco.getDocument()).setDocumentFilter(new CurrencyFilter());
    tfPreco.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            String numericText = tfPreco.getText().replaceAll("[^0-9]", "");
            long value = numericText.isEmpty() ? 0 : Long.parseLong(numericText);
            tfPreco.setText("R$" + (value / 100) + "," + String.format("%02d", value % 100));
        }
    });
}

}


class CurrencyFilter extends DocumentFilter {

    @Override
    public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
        String currentText = fb.getDocument().getText(0, fb.getDocument().getLength());
        String newText = removeNonNumericChars(currentText.substring(0, offset) + text + currentText.substring(offset + length));
        fb.replace(0, fb.getDocument().getLength(), formatCurrency(newText), attrs);
    }

    private String removeNonNumericChars(String text) {
        return text.replaceAll("[^0-9]", "");
    }

    private String formatCurrency(String text) {
        if (text.isEmpty()) {
            return "R$0,00";
        }
        long value = Long.parseLong(text);
        return "R$" + (value / 100) + "," + String.format("%02d", value % 100);
    }
}